name: "Podcast Generator"
author: ""
description: "Generates a feed for a podacst from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The comiter's email address
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: The comiter's name
    required: true
    default: ${{github.actor}}